# Dockerfile para o DevContainer do projeto Java com Maven e Python
# Base image
FROM mcr.microsoft.com/devcontainers/base:bullseye
# As features no devcontainer.json cuidarão da instalação do Java, Maven e Python.