# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from servico_java_monitor.src.main.proto import contrato_pb2 as servico__java__monitor_dot_src_dot_main_dot_proto_dot_contrato__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in servico_java_monitor/src/main/proto/contrato_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MonitorServiceStub(object):
    """Definição do nosso serviço de monitoramento.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnviarDadosSensor = channel.stream_unary(
                '/MonitorService/EnviarDadosSensor',
                request_serializer=servico__java__monitor_dot_src_dot_main_dot_proto_dot_contrato__pb2.SensorData.SerializeToString,
                response_deserializer=servico__java__monitor_dot_src_dot_main_dot_proto_dot_contrato__pb2.StatusResposta.FromString,
                _registered_method=True)


class MonitorServiceServicer(object):
    """Definição do nosso serviço de monitoramento.
    """

    def EnviarDadosSensor(self, request_iterator, context):
        """O cliente envia um FLUXO (stream) de dados do sensor e, ao final,
        o servidor retorna um único StatusResposta.
        Esta é a definição de um "Client Streaming RPC".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnviarDadosSensor': grpc.stream_unary_rpc_method_handler(
                    servicer.EnviarDadosSensor,
                    request_deserializer=servico__java__monitor_dot_src_dot_main_dot_proto_dot_contrato__pb2.SensorData.FromString,
                    response_serializer=servico__java__monitor_dot_src_dot_main_dot_proto_dot_contrato__pb2.StatusResposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MonitorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MonitorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MonitorService(object):
    """Definição do nosso serviço de monitoramento.
    """

    @staticmethod
    def EnviarDadosSensor(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/MonitorService/EnviarDadosSensor',
            servico__java__monitor_dot_src_dot_main_dot_proto_dot_contrato__pb2.SensorData.SerializeToString,
            servico__java__monitor_dot_src_dot_main_dot_proto_dot_contrato__pb2.StatusResposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
