# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import contrato_pb2 as contrato__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in contrato_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MonitorServiceStub(object):
    """Definição do nosso serviço de monitoramento.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistrarUsuario = channel.unary_unary(
                '/MonitorService/RegistrarUsuario',
                request_serializer=contrato__pb2.RegistrarUsuarioRequest.SerializeToString,
                response_deserializer=contrato__pb2.RegistrarUsuarioResponse.FromString,
                _registered_method=True)
        self.RegistrarSensor = channel.unary_unary(
                '/MonitorService/RegistrarSensor',
                request_serializer=contrato__pb2.RegistrarSensorRequest.SerializeToString,
                response_deserializer=contrato__pb2.RegistrarSensorResponse.FromString,
                _registered_method=True)
        self.EnviarDadosSensor = channel.unary_unary(
                '/MonitorService/EnviarDadosSensor',
                request_serializer=contrato__pb2.SensorData.SerializeToString,
                response_deserializer=contrato__pb2.StatusResposta.FromString,
                _registered_method=True)


class MonitorServiceServicer(object):
    """Definição do nosso serviço de monitoramento.
    """

    def RegistrarUsuario(self, request, context):
        """Novo método para registrar um usuário
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistrarSensor(self, request, context):
        """Novo método para registrar um sensor para um usuário
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnviarDadosSensor(self, request, context):
        """O cliente envia uma ÚNICA mensagem de dados do sensor e o servidor retorna um StatusResposta.
        Esta é a definição de um "Unary RPC".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistrarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarUsuario,
                    request_deserializer=contrato__pb2.RegistrarUsuarioRequest.FromString,
                    response_serializer=contrato__pb2.RegistrarUsuarioResponse.SerializeToString,
            ),
            'RegistrarSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarSensor,
                    request_deserializer=contrato__pb2.RegistrarSensorRequest.FromString,
                    response_serializer=contrato__pb2.RegistrarSensorResponse.SerializeToString,
            ),
            'EnviarDadosSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarDadosSensor,
                    request_deserializer=contrato__pb2.SensorData.FromString,
                    response_serializer=contrato__pb2.StatusResposta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MonitorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('MonitorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MonitorService(object):
    """Definição do nosso serviço de monitoramento.
    """

    @staticmethod
    def RegistrarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MonitorService/RegistrarUsuario',
            contrato__pb2.RegistrarUsuarioRequest.SerializeToString,
            contrato__pb2.RegistrarUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistrarSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MonitorService/RegistrarSensor',
            contrato__pb2.RegistrarSensorRequest.SerializeToString,
            contrato__pb2.RegistrarSensorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnviarDadosSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/MonitorService/EnviarDadosSensor',
            contrato__pb2.SensorData.SerializeToString,
            contrato__pb2.StatusResposta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
